---
- name: Listen for API Calls and Trigger DR-Drills
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /trigger
        method: POST
  rules:
    - name: Trigger DR-Drills on Site Status (Up or Down)
      condition: event.data.site_status in ["up", "down"]
      action:
        run_job_template:
          name: Primary-server-frontend-backup
          organization: Default
