---
- name: Listen for API Calls and Trigger DR-Drills
  hosts: localhost
  sources:
    - ansible.eda.http:
        host: 0.0.0.0
        port: 5000
        endpoint: /trigger
        method: POST
  rules:
    - name: Trigger DR-Drills Workflow
      condition: event.data is defined
      action:
        run_job_template:
          name: Primary-server-frontend-backup
          organization: Default
