---
- name: Listen for API Calls and Trigger DR-Drills
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /trigger
        method: POST
  rules:
    - name: R1 - Heard "site-up!"
      condition: event.payload.message == "site-up!"
      action:
        run_job_template:
          name: DR-Drills
          organization: Default

    - name: R2 - Didn't hear "site-up!"
      condition: event.payload.message is defined and event.payload.message != "site-up!"
      action:
        run_job_template:
          name: Primary-server-frontend-backup
          organization: Default
