---
- name: Listen for API Calls and Trigger DR-Drills
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 143.244.142.40
        port: 5000
        endpoint: /trigger
        method: POST
  rules:
    - name: Trigger DR-Drills Workflow
      condition: event.data is defined
      action:
        run_job_template:
          name: Primary-server-frontend-backup
          organization: Default
